---
broker: broker
default_queue: default_queue
result_backend: result_backend
results_expire_in: 123456
redis:
  normal_tasks_poll_period: 1001
  delayed_tasks_poll_period: 23
  delayed_tasks_key: delayed_tasks_key
  master_name: master_name
no_unix_signals: true
